---
title: "First Knit"
author: "Eduardo Noriega"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer  I attended Rosamond High School, and graduated in 2004. I did better in English, than in math, but I always enjoyed my math classes more. I would a 'A' or 'B' in English, but I would get 'B' or 'C' in my math classes. I guess you could say, that I felt like English was easier compared to math, but English was quite boring in high school.
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer I am currently using a Chromebook for all my classes. I also have a Windows laptop as well that my wife purchased a year ago. I would rate myself a 6 or 7 on computer stuff. I am running cable for internet, it claims to be at 200Mbps download speed, and 20Mbps upload.
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer I go by nickname "Eddie." I don't mind being called by first name (Eduardo) at all, whatever is easier.




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer It all depends how hard I work to improve my grades at AVC, while I take courses to transfer to a university. I need to get my bachelor's in nursing, and then work on getting a Master's or Doctorate in nursing; focusing on nurse anesthesia. So far, I have only been looking at Cal. State Fullerton, and Loma Linda University




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer I have been to Honduras and Ecuador. I haven't left the country in 19 years, but I plan on traveling out of the country as soon as I am able. I'm not sure which country, my wife and I, will decide on traveling to first,but I would happy to go to Japan or anywhere in Europe. I have never been in the military, but given my desire to become a nurse anesthesist, I would choose the Army. That role in nursing came from the Army, and I have worked with people that are currently serving and have received help from the Army to advance in their nursing practice to become a nurse anesthesist.  
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer I am taking Math 115 as a requirement for my bachelor's degree. I was not aware that Math 116 would count as actually taking statistics, I will definitley look into that. Thank you for that. I am hoping to learn some things, first and foremost, but yes, an 'A' would look very nice for my G.P.A. I plan to putting in the time and effort to achieve that 'A' and I am pretty confident in doing so. Especially, since I cut my working hours at the hospital to succeed this semester and the upcoming ones.   
  
   
 






  




